var tree = [["QATools",,"",
                [["QATools",,"",
                [["BEM","QATools\/QATools\/BEM.html","",
                [["Annotation","QATools\/QATools\/BEM\/Annotation.html","",
                [["BEMAnnotation","QATools\/QATools\/BEM\/Annotation\/BEMAnnotation.html"," < Annotation",
                [        ]]        ]],["Element","QATools\/QATools\/BEM\/Element.html","",
                [["AbstractPart","QATools\/QATools\/BEM\/Element\/AbstractPart.html","",
                [        ]],["Block","QATools\/QATools\/BEM\/Element\/Block.html"," < AbstractPart",
                [        ]],["Element","QATools\/QATools\/BEM\/Element\/Element.html"," < AbstractPart",
                [        ]],["IBlock","QATools\/QATools\/BEM\/Element\/IBlock.html","",
                [        ]],["IElement","QATools\/QATools\/BEM\/Element\/IElement.html","",
                [        ]],["IPart","QATools\/QATools\/BEM\/Element\/IPart.html","",
                [        ]]        ]],["ElementLocator","QATools\/QATools\/BEM\/ElementLocator.html","",
                [["BEMElementLocator","QATools\/QATools\/BEM\/ElementLocator\/BEMElementLocator.html"," < DefaultElementLocator",
                [        ]],["BEMElementLocatorFactory","QATools\/QATools\/BEM\/ElementLocator\/BEMElementLocatorFactory.html"," < DefaultElementLocatorFactory",
                [        ]],["LocatorHelper","QATools\/QATools\/BEM\/ElementLocator\/LocatorHelper.html","",
                [        ]]        ]],["Exception","QATools\/QATools\/BEM\/Exception.html","",
                [["ElementException","QATools\/QATools\/BEM\/Exception\/ElementException.html"," < ElementException",
                [        ]]        ]],["PropertyDecorator","QATools\/QATools\/BEM\/PropertyDecorator.html","",
                [["BEMPropertyDecorator","QATools\/QATools\/BEM\/PropertyDecorator\/BEMPropertyDecorator.html"," < DefaultPropertyDecorator",
                [        ]]        ]],["Proxy","QATools\/QATools\/BEM\/Proxy.html","",
                [["AbstractPartProxy","QATools\/QATools\/BEM\/Proxy\/AbstractPartProxy.html"," < AbstractProxy",
                [        ]],["BlockProxy","QATools\/QATools\/BEM\/Proxy\/BlockProxy.html"," < AbstractPartProxy",
                [        ]],["ElementProxy","QATools\/QATools\/BEM\/Proxy\/ElementProxy.html"," < AbstractPartProxy",
                [        ]]        ]],["BEMPage","QATools\/QATools\/BEM\/BEMPage.html"," < Page",
                [        ]],["BEMPageFactory","QATools\/QATools\/BEM\/BEMPageFactory.html"," < PageFactory",
                [        ]]        ]],["HtmlElements","QATools\/QATools\/HtmlElements.html","",
                [["Annotation","QATools\/QATools\/HtmlElements\/Annotation.html","",
                [["ElementNameAnnotation","QATools\/QATools\/HtmlElements\/Annotation\/ElementNameAnnotation.html"," < Annotation",
                [        ]]        ]],["Element","QATools\/QATools\/HtmlElements\/Element.html","",
                [["AbstractElementContainer","QATools\/QATools\/HtmlElements\/Element\/AbstractElementContainer.html"," < AbstractTypifiedElement",
                [        ]],["AbstractTypifiedElement","QATools\/QATools\/HtmlElements\/Element\/AbstractTypifiedElement.html","",
                [        ]],["AbstractTypifiedElementCollection","QATools\/QATools\/HtmlElements\/Element\/AbstractTypifiedElementCollection.html"," < AbstractElementCollection",
                [        ]],["Button","QATools\/QATools\/HtmlElements\/Element\/Button.html"," < AbstractTypifiedElement",
                [        ]],["Checkbox","QATools\/QATools\/HtmlElements\/Element\/Checkbox.html"," < LabeledElement",
                [        ]],["FileInput","QATools\/QATools\/HtmlElements\/Element\/FileInput.html"," < AbstractTypifiedElement",
                [        ]],["Form","QATools\/QATools\/HtmlElements\/Element\/Form.html"," < AbstractElementContainer",
                [        ]],["INamed","QATools\/QATools\/HtmlElements\/Element\/INamed.html","",
                [        ]],["ISimpleSetter","QATools\/QATools\/HtmlElements\/Element\/ISimpleSetter.html","",
                [        ]],["ITypifiedElement","QATools\/QATools\/HtmlElements\/Element\/ITypifiedElement.html","",
                [        ]],["LabeledElement","QATools\/QATools\/HtmlElements\/Element\/LabeledElement.html"," < AbstractTypifiedElement",
                [        ]],["Link","QATools\/QATools\/HtmlElements\/Element\/Link.html"," < AbstractTypifiedElement",
                [        ]],["RadioButton","QATools\/QATools\/HtmlElements\/Element\/RadioButton.html"," < LabeledElement",
                [        ]],["RadioGroup","QATools\/QATools\/HtmlElements\/Element\/RadioGroup.html"," < AbstractTypifiedElementCollection",
                [        ]],["Select","QATools\/QATools\/HtmlElements\/Element\/Select.html"," < AbstractTypifiedElement",
                [        ]],["SelectOption","QATools\/QATools\/HtmlElements\/Element\/SelectOption.html"," < AbstractTypifiedElement",
                [        ]],["TextBlock","QATools\/QATools\/HtmlElements\/Element\/TextBlock.html"," < AbstractTypifiedElement",
                [        ]],["TextInput","QATools\/QATools\/HtmlElements\/Element\/TextInput.html"," < AbstractTypifiedElement",
                [        ]]        ]],["Exception","QATools\/QATools\/HtmlElements\/Exception.html","",
                [["FileInputException","QATools\/QATools\/HtmlElements\/Exception\/FileInputException.html"," < TypifiedElementException",
                [        ]],["FormException","QATools\/QATools\/HtmlElements\/Exception\/FormException.html"," < TypifiedElementException",
                [        ]],["RadioGroupException","QATools\/QATools\/HtmlElements\/Exception\/RadioGroupException.html"," < TypifiedElementException",
                [        ]],["SelectException","QATools\/QATools\/HtmlElements\/Exception\/SelectException.html"," < TypifiedElementException",
                [        ]],["TypifiedElementException","QATools\/QATools\/HtmlElements\/Exception\/TypifiedElementException.html"," < ElementException",
                [        ]]        ]],["PropertyDecorator","QATools\/QATools\/HtmlElements\/PropertyDecorator.html","",
                [["TypifiedPropertyDecorator","QATools\/QATools\/HtmlElements\/PropertyDecorator\/TypifiedPropertyDecorator.html"," < DefaultPropertyDecorator",
                [        ]]        ]],["Proxy","QATools\/QATools\/HtmlElements\/Proxy.html","",
                [["TypifiedElementProxy","QATools\/QATools\/HtmlElements\/Proxy\/TypifiedElementProxy.html"," < AbstractProxy",
                [        ]]        ]],["TypifiedPage","QATools\/QATools\/HtmlElements\/TypifiedPage.html"," < Page",
                [        ]],["TypifiedPageFactory","QATools\/QATools\/HtmlElements\/TypifiedPageFactory.html"," < PageFactory",
                [        ]]        ]],["PageObject","QATools\/QATools\/PageObject.html","",
                [["Annotation","QATools\/QATools\/PageObject\/Annotation.html","",
                [["FindByAnnotation","QATools\/QATools\/PageObject\/Annotation\/FindByAnnotation.html"," < Annotation",
                [        ]],["PageUrlAnnotation","QATools\/QATools\/PageObject\/Annotation\/PageUrlAnnotation.html"," < Annotation",
                [        ]],["TimeoutAnnotation","QATools\/QATools\/PageObject\/Annotation\/TimeoutAnnotation.html"," < Annotation",
                [        ]]        ]],["Config","QATools\/QATools\/PageObject\/Config.html","",
                [["Config","QATools\/QATools\/PageObject\/Config\/Config.html","",
                [        ]],["IConfig","QATools\/QATools\/PageObject\/Config\/IConfig.html","",
                [        ]]        ]],["Element","QATools\/QATools\/PageObject\/Element.html","",
                [["AbstractElementCollection","QATools\/QATools\/PageObject\/Element\/AbstractElementCollection.html","",
                [        ]],["AbstractElementContainer","QATools\/QATools\/PageObject\/Element\/AbstractElementContainer.html"," < WebElement",
                [        ]],["IContainerAware","QATools\/QATools\/PageObject\/Element\/IContainerAware.html","",
                [        ]],["IElementContainer","QATools\/QATools\/PageObject\/Element\/IElementContainer.html","",
                [        ]],["INodeElementAware","QATools\/QATools\/PageObject\/Element\/INodeElementAware.html","",
                [        ]],["IWebElement","QATools\/QATools\/PageObject\/Element\/IWebElement.html","",
                [        ]],["WebElement","QATools\/QATools\/PageObject\/Element\/WebElement.html"," < NodeElement",
                [        ]],["WebElementCollection","QATools\/QATools\/PageObject\/Element\/WebElementCollection.html"," < AbstractElementCollection",
                [        ]]        ]],["ElementLocator","QATools\/QATools\/PageObject\/ElementLocator.html","",
                [["DefaultElementLocator","QATools\/QATools\/PageObject\/ElementLocator\/DefaultElementLocator.html","",
                [        ]],["DefaultElementLocatorFactory","QATools\/QATools\/PageObject\/ElementLocator\/DefaultElementLocatorFactory.html","",
                [        ]],["IElementLocator","QATools\/QATools\/PageObject\/ElementLocator\/IElementLocator.html","",
                [        ]],["IElementLocatorFactory","QATools\/QATools\/PageObject\/ElementLocator\/IElementLocatorFactory.html","",
                [        ]],["WaitingElementLocator","QATools\/QATools\/PageObject\/ElementLocator\/WaitingElementLocator.html"," < DefaultElementLocator",
                [        ]]        ]],["Exception","QATools\/QATools\/PageObject\/Exception.html","",
                [["AnnotationException","QATools\/QATools\/PageObject\/Exception\/AnnotationException.html"," < PageFactoryException",
                [        ]],["ConfigException","QATools\/QATools\/PageObject\/Exception\/ConfigException.html"," < PageFactoryException",
                [        ]],["ElementCollectionException","QATools\/QATools\/PageObject\/Exception\/ElementCollectionException.html"," < ElementException",
                [        ]],["ElementException","QATools\/QATools\/PageObject\/Exception\/ElementException.html"," < PageFactoryException",
                [        ]],["ElementNotFoundException","QATools\/QATools\/PageObject\/Exception\/ElementNotFoundException.html"," < ElementException",
                [        ]],["PageException","QATools\/QATools\/PageObject\/Exception\/PageException.html"," < PageFactoryException",
                [        ]],["PageFactoryException","QATools\/QATools\/PageObject\/Exception\/PageFactoryException.html"," < Exception",
                [        ]],["UrlException","QATools\/QATools\/PageObject\/Exception\/UrlException.html"," < PageFactoryException",
                [        ]]        ]],["PropertyDecorator","QATools\/QATools\/PageObject\/PropertyDecorator.html","",
                [["DefaultPropertyDecorator","QATools\/QATools\/PageObject\/PropertyDecorator\/DefaultPropertyDecorator.html","",
                [        ]],["IPropertyDecorator","QATools\/QATools\/PageObject\/PropertyDecorator\/IPropertyDecorator.html","",
                [        ]]        ]],["Proxy","QATools\/QATools\/PageObject\/Proxy.html","",
                [["AbstractProxy","QATools\/QATools\/PageObject\/Proxy\/AbstractProxy.html"," < AbstractElementCollection",
                [        ]],["IProxy","QATools\/QATools\/PageObject\/Proxy\/IProxy.html","",
                [        ]],["WebElementProxy","QATools\/QATools\/PageObject\/Proxy\/WebElementProxy.html"," < AbstractProxy",
                [        ]]        ]],["Url","QATools\/QATools\/PageObject\/Url.html","",
                [["Builder","QATools\/QATools\/PageObject\/Url\/Builder.html","",
                [        ]],["IBuilder","QATools\/QATools\/PageObject\/Url\/IBuilder.html","",
                [        ]],["IUrlFactory","QATools\/QATools\/PageObject\/Url\/IUrlFactory.html","",
                [        ]],["Normalizer","QATools\/QATools\/PageObject\/Url\/Normalizer.html","",
                [        ]],["Parser","QATools\/QATools\/PageObject\/Url\/Parser.html","",
                [        ]],["UrlFactory","QATools\/QATools\/PageObject\/Url\/UrlFactory.html","",
                [        ]]        ]],["How","QATools\/QATools\/PageObject\/How.html","",
                [        ]],["IPageFactory","QATools\/QATools\/PageObject\/IPageFactory.html","",
                [        ]],["ISearchContext","QATools\/QATools\/PageObject\/ISearchContext.html","",
                [        ]],["Page","QATools\/QATools\/PageObject\/Page.html"," < DocumentElement",
                [        ]],["PageFactory","QATools\/QATools\/PageObject\/PageFactory.html","",
                [        ]],["Property","QATools\/QATools\/PageObject\/Property.html"," < ReflectionProperty",
                [        ]],["SeleniumSelector","QATools\/QATools\/PageObject\/SeleniumSelector.html","",
                [        ]]        ]]        ]]        ]]        ]

